### PR TITLE
Fixed: Failed load command Rake

### PR DESCRIPTION
**Pull request by luizpicolo**
ERROR: bundler: failed to load command: rake (/usr/local/bin/rake)

### CODE REVIEW

**Comment by beydogan** [comment]
@luizpicolo my docker is building fine without this line. Where is it failing on your end?

**Comment by luizpicolo** [comment]
Hello @beydogan. 

The error `ERROR: bundler: failed to load command: rake (/ usr / local / bin / rake)`  happens when the `bundle install` tries to run. Because the bundler is not installed, this error occurs. So, this line is meant to install the bundler before so that this error does not occur.

Of course, if the bundler is already installed, this error will not occur

**Comment by beydogan** [comment]
Yes, thats correct but it shouldn't depend on host machine since Dockerfile is using the docker image `ruby:2.3.3`, I assume, by default it comes with bundler installed. I'm no expert at docker, just trying to find out :)

**Comment by luizpicolo** [comment]
No problem :). Here, this line healed my problem: P, but maybe you are right and VHost by default should be with all dependencies installed. But when I create a new APP in dokku and I use dokku-api, this error follows me

**Comment by beydogan** [comment]
Ah! Now it makes sense, I thought you were having this error on your dev machine. See this comment: https://github.com/dokku/dokku-api/issues/7#issuecomment-355552897

dokku-api should not use Dockerfile deployment. If you deploy again with latest code it should work as expected.

**Comment by luizpicolo** [comment]
Like this. Well, I'll test then on a new possibility and return with my feedback.

**Comment by beydogan** [comment]
So I will close this for now, thank you for the PR and help.

**Pull request closed without merging**
